runmode: debug
general:
    addr: :9080
    dsn: root:123456@(192.168.188.106:3306)/lyanna?charset=utf8&parseTime=True&loc=Local
    sessionsecret: lyanna_blog
    logoutenabled: true
    perpage: 10

github:
    clientid: 6b61462cd8f0807f09a0
    clientsecret: 93bfae7774a3bbd511a0f7eff996b9963cbfd61e
    authurl: https://github.com/login/oauth/authorize?client_id=%s&scope=user:email&state=%s
    # 与github配置的回调地址一致
    redirecturl: http://127.0.0.1:9080/oauth2
    tokenurl: https://github.com/login/oauth/access_token
log:
    logpath: ./logs/callin.log
    maxsize: 20
    maxage: 7
    compress: true
    maxbackups: 10